version: '3.7'

services:
  app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - '127.0.0.1:${APP_PORT}:80'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
